<a href="https://colab.research.google.com/github/yewonhn/My-AI-Lab/blob/main/3%EC%A3%BC%EC%B0%A8/Data_Classficasion_heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 데이터 불러오기

In [1]:
import pandas as pd
import numpy as np  # 늘 있을 것.

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

# 2. 독립변수 만들기

In [ ]:
X = df.drop('target',axis=1)      # 타겟 레이블 제외하고 X에 넣기 (타겟과 나머지를 나눌 것이라서)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [ ]:
y = df['target']   # 타겟만 떼서 붙임
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

## 3. 훈련 데이터와 테스트 데이터로 분리

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X,
                                                  y,
                                                  test_size=0.2,    # 테스트는 20% 분량 준다는 것.
                                                  shuffle=True,
                                                  random_state=12)
print(X_train.shape, y_train.shape)  # 훈련 데이터 수
print(X_test.shape, y_test.shape)    # 테스트 데이터 수

(242, 13) (242,)
(61, 13) (61,)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

## 4.인공지능 모델에게 데이터 학습시키기

In [ ]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.7213114754098361
[[21 10]
 [ 7 23]]

In [ ]:
LogisticRegression()

In [ ]:
print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)

print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Radom Forest ---
0.819672131147541
[[23  8]
 [ 3 27]]

In [ ]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))