<a href="https://colab.research.google.com/github/yewonhn/My-AI-Lab/blob/main/3%EC%A3%BC%EC%B0%A8/Data_Regression_heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np  # 늘 있을 것.

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
X = df.drop('target',axis=1)  # 타겟 제외 나머지 컬럼
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [4]:
X = df.drop('age',axis=1)   # 나이 제외 나머지 컬럼
X.head()

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
y = df['age']   # 나이만 떼서 붙임
y.head()

0    63
1    37
2    41
3    56
4    57
Name: age, dtype: int64

## 3. 훈련 데이터와 테스트 데이터로 분리

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X,
                                                  y,
                                                  test_size=0.2,    # 테스트는 20% 분량 준다는 것.
                                                  shuffle=True,
                                                  random_state=12)
print(X_train.shape, y_train.shape)  # 훈련 데이터 수
print(X_test.shape, y_test.shape)    # 테스트 데이터 수

(242, 13) (242,)
(61, 13) (61,)

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.metrics import mean_squared_error

In [12]:
model = LinearRegression()
model.fit(X_train, y_train)
ly_preds = model.predict(X_test)

print('평균제곱근오차', mean_squared_error(ly_preds, y_test))

def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)

print('평균제곱근오차', mse_np(ly_preds, y_test))

def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2for a, p in zip(actual, predicted))
    mean_square_error = sum_square_error / len(actual)
    return mean_square_error

print('평균제곱근오차', mse(ly_preds, y_test))

평균제곱근오차 45.01521547675206
평균제곱근오차 45.01521547675206
평균제곱근오차 45.01521547675206

<>:13: SyntaxWarning: invalid decimal literal
<>:13: SyntaxWarning: invalid decimal literal
/tmp/ipykernel_8485/2036977504.py:13: SyntaxWarning: invalid decimal literal
  sum_square_error = sum((a - p) ** 2for a, p in zip(actual, predicted))

In [15]:
# 1. 모델 생성
lr_reg = LinearRegression()
dt_reg = DecisionTreeRegressor(random_state=0)
rf_reg = RandomForestRegressor(random_state=0)

# 2. 모델 학습
lr_reg.fit(X_train, y_train)
dt_reg.fit(X_train, y_train)
rf_reg.fit(X_train, y_train)

# 3. 예측 및 평가
models = [lr_reg, dt_reg, rf_reg]
for model in models:
    pred = model.predict(X_test)
    name = model.__class__.__name__
    mae = mean_absolute_error(y_test, pred)
    r2 = r2_score(y_test, pred)

    print(f"--- {name} ---")
    print(f"Mean Absolute Error (MAE): {mae:.2f}")
    print(f"R2 Score: {r2:.2f}\n")

--- LinearRegression ---
Mean Absolute Error (MAE): 5.45
R2 Score: 0.25

--- DecisionTreeRegressor ---
Mean Absolute Error (MAE): 8.62
R2 Score: -0.83

--- RandomForestRegressor ---
Mean Absolute Error (MAE): 5.39
R2 Score: 0.23